### ISSUE TITLE
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module

### ISSUE THREAD

**Issue by yash88600** [guanlongzhao/fac-via-ppg#5]
Hi, I am trying to follow the instruction on google colab however with this "./run_coverage.sh" I am getting the following error: 

nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
EEEEE
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (decode.py, line 23))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/content/fac-via-ppg/test/test_align.py", line 16, in <module>
    from common import align
  File "/content/fac-via-ppg/src/common/__init__.py", line 1, in <module>
    from .decode import *
  File "/content/fac-via-ppg/src/common/decode.py", line 23
    def read_nnet3_model(model_path: str) -> nnet3.Nnet:
                                   ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (decode.py, line 23))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/content/fac-via-ppg/test/test_decode.py", line 16, in <module>
    from common import decode
  File "/content/fac-via-ppg/src/common/__init__.py", line 1, in <module>
    from .decode import *
  File "/content/fac-via-ppg/src/common/decode.py", line 23
    def read_nnet3_model(model_path: str) -> nnet3.Nnet:
                                   ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (decode.py, line 23))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/content/fac-via-ppg/test/test_feat.py", line 16, in <module>
    from common import feat
  File "/content/fac-via-ppg/src/common/__init__.py", line 1, in <module>
    from .decode import *
  File "/content/fac-via-ppg/src/common/decode.py", line 23
    def read_nnet3_model(model_path: str) -> nnet3.Nnet:
                                   ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (compute_ppg.py, line 42))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/content/fac-via-ppg/test/test_ppg.py", line 16, in <module>
    import ppg
  File "/content/fac-via-ppg/src/ppg/__init__.py", line 1, in <module>
    from .compute_ppg import *
  File "/content/fac-via-ppg/src/ppg/compute_ppg.py", line 42
    def compute_full_ppg(nnet: Nnet, feats: Matrix) -> Matrix:
                             ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (decode.py, line 23))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/content/fac-via-ppg/test/test_utterance.py", line 19, in <module>
    from common import utterance
  File "/content/fac-via-ppg/src/common/__init__.py", line 1, in <module>
    from .decode import *
  File "/content/fac-via-ppg/src/common/decode.py", line 23
    def read_nnet3_model(model_path: str) -> nnet3.Nnet:
                                   ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)

for the export , i have used the following command as the provided command wasn't working for me:
! echo $PYTHONPATH
import os
os.environ['PYTHONPATH'] += ":/face-via-ppg/src"

and to make the script executable as mentioned in the readme i have used :
!chmod +x run_coverage.sh 

Would be great if I can get help ASAP!!

Thanks in Advance

**Comment by guanlongzhao** [comment]
I think the error message explains itself,
>Coverage not available: unable to import coverage module

Also, the test scripts rely on `nose` to provide the coverage info, which is not required for the model training and inference. You can probably skip the test coverage step.
I haven't run this version of the code on colab yet, but you probably already know that colab uses a lot of magic to make it look like a Unix-like environment but it is not. If you use colab then you probably need to customize the code yourself a bit. That been said, I have done experiments with the core parts of the codebase on colab (some internal code not shared here) and they ran fine.
